-- +goose Up
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- 1. 外部キー制約の一旦削除
-- ============================================================
ALTER TABLE attachments DROP CONSTRAINT IF EXISTS attachments_user_id_fkey;
ALTER TABLE identifications DROP CONSTRAINT IF EXISTS identifications_user_id_fkey;
ALTER TABLE make_specimen DROP CONSTRAINT IF EXISTS make_specimen_user_id_fkey;
ALTER TABLE observations DROP CONSTRAINT IF EXISTS observations_user_id_fkey;
ALTER TABLE occurrence DROP CONSTRAINT IF EXISTS occurrence_user_id_fkey;
ALTER TABLE occurrence DROP CONSTRAINT IF EXISTS occurrence_workstation_id_fkey;
ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_user_id_fkey;
ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_project_id_fkey;
ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_workstation_id_fkey;
ALTER TABLE wiki_pages DROP CONSTRAINT IF EXISTS wiki_pages_user_id_fkey;
ALTER TABLE wiki_pages DROP CONSTRAINT IF EXISTS wiki_pages_workstation_id_fkey;
ALTER TABLE observation_methods DROP CONSTRAINT IF EXISTS observation_methods_pageid_fkey;
ALTER TABLE specimen_methods DROP CONSTRAINT IF EXISTS specimen_methods_page_id_fkey;
ALTER TABLE workstation_user DROP CONSTRAINT IF EXISTS workstation_user_user_id_fkey;
ALTER TABLE workstation_user DROP CONSTRAINT IF EXISTS workstation_user_workstation_id_fkey;


-- ============================================================
-- 2. User & Workstation: UUID(text) -> 自動連番(BigInt)
-- ============================================================

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey CASCADE;
ALTER TABLE users DROP COLUMN IF EXISTS user_id;
ALTER TABLE users ADD COLUMN user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE workstation DROP CONSTRAINT IF EXISTS workstation_pkey CASCADE;
ALTER TABLE workstation DROP COLUMN IF EXISTS workstation_id;
ALTER TABLE workstation ADD COLUMN workstation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE workstation_user DROP CONSTRAINT IF EXISTS workstation_user_pkey;
ALTER TABLE workstation_user DROP COLUMN IF EXISTS user_id;
ALTER TABLE workstation_user DROP COLUMN IF EXISTS workstation_id;
ALTER TABLE workstation_user ADD COLUMN user_id BIGINT NOT NULL;
ALTER TABLE workstation_user ADD COLUMN workstation_id BIGINT NOT NULL;
ALTER TABLE workstation_user ADD CONSTRAINT workstation_user_pkey PRIMARY KEY (workstation_id, user_id);
ALTER TABLE workstation_user ADD CONSTRAINT workstation_user_workstation_id_fkey FOREIGN KEY (workstation_id) REFERENCES workstation(workstation_id) ON DELETE CASCADE;
ALTER TABLE workstation_user ADD CONSTRAINT workstation_user_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;


-- ============================================================
-- 3. Projects, WikiPagesなど: 自動連番(Int) -> UUID(Text)
-- ============================================================

ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_pkey CASCADE;
ALTER TABLE projects ALTER COLUMN project_id DROP DEFAULT;
ALTER TABLE projects ALTER COLUMN project_id TYPE text USING gen_random_uuid()::text;
ALTER TABLE projects ALTER COLUMN project_id SET DEFAULT gen_random_uuid()::text;
ALTER TABLE projects ADD CONSTRAINT projects_pkey PRIMARY KEY (project_id);

ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_pkey CASCADE;
ALTER TABLE project_members ALTER COLUMN project_member_id DROP DEFAULT;
ALTER TABLE project_members ALTER COLUMN project_member_id TYPE text USING gen_random_uuid()::text;
ALTER TABLE project_members ALTER COLUMN project_member_id SET DEFAULT gen_random_uuid()::text;
ALTER TABLE project_members ADD CONSTRAINT project_members_pkey PRIMARY KEY (project_member_id);
ALTER TABLE project_members ALTER COLUMN project_id TYPE text USING NULL;
ALTER TABLE project_members ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE project_members ALTER COLUMN workstation_id TYPE bigint USING NULL;
ALTER TABLE project_members ADD CONSTRAINT project_members_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(project_id);
ALTER TABLE project_members ADD CONSTRAINT project_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);
ALTER TABLE project_members ADD CONSTRAINT project_members_workstation_id_fkey FOREIGN KEY (workstation_id) REFERENCES workstation(workstation_id);

ALTER TABLE wiki_pages DROP CONSTRAINT IF EXISTS wiki_pages_pkey CASCADE;
ALTER TABLE wiki_pages ALTER COLUMN page_id DROP DEFAULT;
ALTER TABLE wiki_pages ALTER COLUMN page_id TYPE text USING gen_random_uuid()::text;
ALTER TABLE wiki_pages ALTER COLUMN page_id SET DEFAULT gen_random_uuid()::text;
ALTER TABLE wiki_pages ADD CONSTRAINT wiki_pages_pkey PRIMARY KEY (page_id);
ALTER TABLE wiki_pages ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE wiki_pages ALTER COLUMN workstation_id TYPE bigint USING NULL;
ALTER TABLE wiki_pages ADD CONSTRAINT wiki_pages_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);
ALTER TABLE wiki_pages ADD CONSTRAINT wiki_pages_workstation_id_fkey FOREIGN KEY (workstation_id) REFERENCES workstation(workstation_id);

ALTER TABLE observation_methods DROP CONSTRAINT IF EXISTS observation_methods_pkey CASCADE;
ALTER TABLE observation_methods ALTER COLUMN observation_method_id DROP DEFAULT;
ALTER TABLE observation_methods ALTER COLUMN observation_method_id TYPE text USING gen_random_uuid()::text;
ALTER TABLE observation_methods ALTER COLUMN observation_method_id SET DEFAULT gen_random_uuid()::text;
ALTER TABLE observation_methods ADD CONSTRAINT observation_methods_pkey PRIMARY KEY (observation_method_id);
ALTER TABLE observation_methods ALTER COLUMN pageid TYPE text USING NULL;
ALTER TABLE observation_methods ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE observation_methods ALTER COLUMN workstation_id TYPE bigint USING NULL;
ALTER TABLE observation_methods ADD CONSTRAINT observation_methods_pageid_fkey FOREIGN KEY (pageid) REFERENCES wiki_pages(page_id);

ALTER TABLE specimen_methods ALTER COLUMN page_id TYPE text USING NULL;
ALTER TABLE specimen_methods ADD CONSTRAINT specimen_methods_page_id_fkey FOREIGN KEY (page_id) REFERENCES wiki_pages(page_id);


-- ============================================================
-- 4. Attachment Group の修正とリネーム（ここを修正したのだ！）
-- ============================================================
DROP TABLE IF EXISTS attachment_group;
ALTER TABLE attachment_goup RENAME TO attachment_group;

-- ★追加: 古いテーブル名(goup)の時に付いていたPK制約を削除するのだ
ALTER TABLE attachment_group DROP CONSTRAINT IF EXISTS attachment_goup_pkey;

ALTER TABLE attachment_group ALTER COLUMN occurrence_id TYPE text USING occurrence_id::text;
ALTER TABLE attachment_group ALTER COLUMN attachment_id TYPE text USING attachment_id::text;
ALTER TABLE attachment_group ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE attachment_group ALTER COLUMN workstation_id TYPE bigint USING NULL;

ALTER TABLE attachment_group ADD CONSTRAINT attachment_group_pkey PRIMARY KEY (occurrence_id, attachment_id);
ALTER TABLE attachment_group ADD CONSTRAINT attachment_group_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES occurrence(occurrence_id) ON DELETE CASCADE;
ALTER TABLE attachment_group ADD CONSTRAINT attachment_group_attachment_id_fkey FOREIGN KEY (attachment_id) REFERENCES attachments(attachment_id) ON DELETE CASCADE;


-- ============================================================
-- 5. その他のテーブルの参照カラムを一括更新 (Text -> BigInt)
-- ============================================================

ALTER TABLE attachments ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE attachments ADD CONSTRAINT attachments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);

ALTER TABLE identifications ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE identifications ADD CONSTRAINT identifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);

ALTER TABLE make_specimen ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE make_specimen ADD CONSTRAINT make_specimen_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);

ALTER TABLE observations ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE observations ADD CONSTRAINT observations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);

ALTER TABLE occurrence ALTER COLUMN user_id TYPE bigint USING NULL;
ALTER TABLE occurrence ALTER COLUMN workstation_id TYPE bigint USING NULL;
ALTER TABLE occurrence ADD CONSTRAINT occurrence_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);
ALTER TABLE occurrence ADD CONSTRAINT occurrence_workstation_id_fkey FOREIGN KEY (workstation_id) REFERENCES workstation(workstation_id);

-- +goose Down
-- This migration is destructive.
