--
-- PostgreSQL database dump
--

\restrict BNK9tzMTJm5GiO5D1GBcLe0ffZdi4Vjgf8mMb62rfielcvhoL1woaZeXsrfBsGm

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attachment_goup; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.attachment_goup (
    occurrence_id integer NOT NULL,
    attachment_id integer NOT NULL,
    priority integer,
    workstation_id integer,
    user_id integer
);


ALTER TABLE public.attachment_goup OWNER TO admin;

--
-- Name: attachment_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.attachment_group (
    occurrence_id text NOT NULL,
    attachment_id text NOT NULL,
    priority integer
);


ALTER TABLE public.attachment_group OWNER TO admin;

--
-- Name: attachments; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.attachments (
    attachment_id text NOT NULL,
    file_path text,
    user_id text
);


ALTER TABLE public.attachments OWNER TO admin;

--
-- Name: classification_json; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.classification_json (
    classification_id text NOT NULL,
    class_classification jsonb
);


ALTER TABLE public.classification_json OWNER TO admin;

--
-- Name: file_extensions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.file_extensions (
    extension_id integer NOT NULL,
    extension_text character varying(255),
    file_type_id integer
);


ALTER TABLE public.file_extensions OWNER TO admin;

--
-- Name: file_extensions_extension_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.file_extensions_extension_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.file_extensions_extension_id_seq OWNER TO admin;

--
-- Name: file_extensions_extension_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.file_extensions_extension_id_seq OWNED BY public.file_extensions.extension_id;


--
-- Name: file_types; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.file_types (
    file_type_id integer NOT NULL,
    type_name text
);


ALTER TABLE public.file_types OWNER TO admin;

--
-- Name: file_types_file_type_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.file_types_file_type_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.file_types_file_type_id_seq OWNER TO admin;

--
-- Name: file_types_file_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.file_types_file_type_id_seq OWNED BY public.file_types.file_type_id;


--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO admin;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: identifications; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.identifications (
    identification_id text NOT NULL,
    occurrence_id text,
    user_id text,
    source_info text,
    identificated_at timestamp with time zone
);


ALTER TABLE public.identifications OWNER TO admin;

--
-- Name: languages; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.languages (
    language_id integer NOT NULL,
    language_short text,
    language_common text
);


ALTER TABLE public.languages OWNER TO admin;

--
-- Name: language_language_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.language_language_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.language_language_id_seq OWNER TO admin;

--
-- Name: language_language_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.language_language_id_seq OWNED BY public.languages.language_id;


--
-- Name: make_specimen; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.make_specimen (
    make_specimen_id text NOT NULL,
    specimen_id text,
    user_id text,
    created_at timestamp with time zone
);


ALTER TABLE public.make_specimen OWNER TO admin;

--
-- Name: observation_methods; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.observation_methods (
    observation_method_id integer NOT NULL,
    method_common_name text,
    pageid integer,
    workstation_id integer,
    user_id integer
);


ALTER TABLE public.observation_methods OWNER TO admin;

--
-- Name: observation_methods_observation_method_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.observation_methods_observation_method_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.observation_methods_observation_method_id_seq OWNER TO admin;

--
-- Name: observation_methods_observation_method_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.observation_methods_observation_method_id_seq OWNED BY public.observation_methods.observation_method_id;


--
-- Name: observations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.observations (
    observation_id text NOT NULL,
    occurrence_id text,
    user_id text,
    observation_method_id text,
    behavior text,
    observed_at timestamp with time zone
);


ALTER TABLE public.observations OWNER TO admin;

--
-- Name: occurrence; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.occurrence (
    occurrence_id text NOT NULL,
    workstation_id text,
    user_id text,
    project_id text,
    individual_id text,
    lifestage text,
    sex text,
    body_length numeric,
    note text,
    classification_id text,
    place_id text,
    language_id text,
    created_at timestamp with time zone,
    timezone text
);


ALTER TABLE public.occurrence OWNER TO admin;

--
-- Name: place_names_json; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.place_names_json (
    place_name_id text NOT NULL,
    class_place_name jsonb
);


ALTER TABLE public.place_names_json OWNER TO admin;

--
-- Name: places; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.places (
    place_id text NOT NULL,
    place_name_id text,
    coordinates jsonb,
    accuracy numeric
);


ALTER TABLE public.places OWNER TO admin;

--
-- Name: project_members; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project_members (
    project_member_id integer NOT NULL,
    project_id integer,
    user_id integer,
    join_day date,
    finish_day date,
    workstation_id integer
);


ALTER TABLE public.project_members OWNER TO admin;

--
-- Name: project_members_project_member_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.project_members_project_member_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.project_members_project_member_id_seq OWNER TO admin;

--
-- Name: project_members_project_member_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.project_members_project_member_id_seq OWNED BY public.project_members.project_member_id;


--
-- Name: projects; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.projects (
    project_id integer NOT NULL,
    project_name text NOT NULL,
    disscription text,
    start_day date,
    finished_day date,
    updated_day date,
    note text,
    workstation_id integer,
    user_id integer
);


ALTER TABLE public.projects OWNER TO admin;

--
-- Name: projects_project_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.projects_project_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.projects_project_id_seq OWNER TO admin;

--
-- Name: projects_project_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.projects_project_id_seq OWNED BY public.projects.project_id;


--
-- Name: specimen; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.specimen (
    specimen_id text NOT NULL,
    occurrence_id text,
    institution_id text,
    collection_id text,
    specimen_method_id text
);


ALTER TABLE public.specimen OWNER TO admin;

--
-- Name: specimen_methods; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.specimen_methods (
    specimen_methods_id integer NOT NULL,
    method_common_name text,
    page_id integer,
    workstation_id integer,
    user_id integer
);


ALTER TABLE public.specimen_methods OWNER TO admin;

--
-- Name: specimen_methods_specimen_methods_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.specimen_methods_specimen_methods_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.specimen_methods_specimen_methods_id_seq OWNER TO admin;

--
-- Name: specimen_methods_specimen_methods_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.specimen_methods_specimen_methods_id_seq OWNED BY public.specimen_methods.specimen_methods_id;


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_roles (
    role_id integer NOT NULL,
    role_name text NOT NULL
);


ALTER TABLE public.user_roles OWNER TO admin;

--
-- Name: user_roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.user_roles_role_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_roles_role_id_seq OWNER TO admin;

--
-- Name: user_roles_role_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.user_roles_role_id_seq OWNED BY public.user_roles.role_id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    user_id text NOT NULL,
    user_name text NOT NULL,
    display_name text,
    mail_address text,
    password text,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: wiki_pages; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.wiki_pages (
    page_id integer NOT NULL,
    title text,
    user_id integer,
    created_date timestamp without time zone DEFAULT now(),
    updated_date timestamp without time zone,
    content_path text,
    workstation_id integer
);


ALTER TABLE public.wiki_pages OWNER TO admin;

--
-- Name: wiki_pages_page_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.wiki_pages_page_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wiki_pages_page_id_seq OWNER TO admin;

--
-- Name: wiki_pages_page_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.wiki_pages_page_id_seq OWNED BY public.wiki_pages.page_id;


--
-- Name: workstation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.workstation (
    workstation_id text NOT NULL,
    workstation_name text NOT NULL
);


ALTER TABLE public.workstation OWNER TO admin;

--
-- Name: workstation_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.workstation_user (
    workstation_id text NOT NULL,
    user_id text NOT NULL,
    role_id integer DEFAULT 1
);


ALTER TABLE public.workstation_user OWNER TO admin;

--
-- Name: file_extensions extension_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.file_extensions ALTER COLUMN extension_id SET DEFAULT nextval('public.file_extensions_extension_id_seq'::regclass);


--
-- Name: file_types file_type_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.file_types ALTER COLUMN file_type_id SET DEFAULT nextval('public.file_types_file_type_id_seq'::regclass);


--
-- Name: languages language_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.languages ALTER COLUMN language_id SET DEFAULT nextval('public.language_language_id_seq'::regclass);


--
-- Name: observation_methods observation_method_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.observation_methods ALTER COLUMN observation_method_id SET DEFAULT nextval('public.observation_methods_observation_method_id_seq'::regclass);


--
-- Name: project_members project_member_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project_members ALTER COLUMN project_member_id SET DEFAULT nextval('public.project_members_project_member_id_seq'::regclass);


--
-- Name: projects project_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.projects ALTER COLUMN project_id SET DEFAULT nextval('public.projects_project_id_seq'::regclass);


--
-- Name: specimen_methods specimen_methods_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.specimen_methods ALTER COLUMN specimen_methods_id SET DEFAULT nextval('public.specimen_methods_specimen_methods_id_seq'::regclass);


--
-- Name: user_roles role_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_roles ALTER COLUMN role_id SET DEFAULT nextval('public.user_roles_role_id_seq'::regclass);


--
-- Name: wiki_pages page_id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wiki_pages ALTER COLUMN page_id SET DEFAULT nextval('public.wiki_pages_page_id_seq'::regclass);


--
-- Name: attachment_goup attachment_goup_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachment_goup
    ADD CONSTRAINT attachment_goup_pkey PRIMARY KEY (occurrence_id, attachment_id);


--
-- Name: attachment_group attachment_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachment_group
    ADD CONSTRAINT attachment_group_pkey PRIMARY KEY (occurrence_id, attachment_id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (attachment_id);


--
-- Name: classification_json classification_json_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.classification_json
    ADD CONSTRAINT classification_json_pkey PRIMARY KEY (classification_id);


--
-- Name: file_extensions file_extensions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.file_extensions
    ADD CONSTRAINT file_extensions_pkey PRIMARY KEY (extension_id);


--
-- Name: file_types file_types_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.file_types
    ADD CONSTRAINT file_types_pkey PRIMARY KEY (file_type_id);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: identifications identifications_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.identifications
    ADD CONSTRAINT identifications_pkey PRIMARY KEY (identification_id);


--
-- Name: languages language_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT language_pkey PRIMARY KEY (language_id);


--
-- Name: make_specimen make_specimen_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.make_specimen
    ADD CONSTRAINT make_specimen_pkey PRIMARY KEY (make_specimen_id);


--
-- Name: observation_methods observation_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.observation_methods
    ADD CONSTRAINT observation_methods_pkey PRIMARY KEY (observation_method_id);


--
-- Name: observations observations_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_pkey PRIMARY KEY (observation_id);


--
-- Name: occurrence occurrence_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_pkey PRIMARY KEY (occurrence_id);


--
-- Name: place_names_json place_names_json_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.place_names_json
    ADD CONSTRAINT place_names_json_pkey PRIMARY KEY (place_name_id);


--
-- Name: places places_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (place_id);


--
-- Name: project_members project_members_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_pkey PRIMARY KEY (project_member_id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (project_id);


--
-- Name: specimen_methods specimen_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.specimen_methods
    ADD CONSTRAINT specimen_methods_pkey PRIMARY KEY (specimen_methods_id);


--
-- Name: specimen specimen_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.specimen
    ADD CONSTRAINT specimen_pkey PRIMARY KEY (specimen_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (role_id);


--
-- Name: user_roles user_roles_role_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_role_name_key UNIQUE (role_name);


--
-- Name: users users_mail_address_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_mail_address_key UNIQUE (mail_address);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: wiki_pages wiki_pages_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wiki_pages
    ADD CONSTRAINT wiki_pages_pkey PRIMARY KEY (page_id);


--
-- Name: workstation workstation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.workstation
    ADD CONSTRAINT workstation_pkey PRIMARY KEY (workstation_id);


--
-- Name: workstation_user workstation_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.workstation_user
    ADD CONSTRAINT workstation_user_pkey PRIMARY KEY (workstation_id, user_id);


--
-- Name: attachment_group attachment_group_attachment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachment_group
    ADD CONSTRAINT attachment_group_attachment_id_fkey FOREIGN KEY (attachment_id) REFERENCES public.attachments(attachment_id) ON DELETE CASCADE;


--
-- Name: attachment_group attachment_group_occurrence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachment_group
    ADD CONSTRAINT attachment_group_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES public.occurrence(occurrence_id) ON DELETE CASCADE;


--
-- Name: attachments attachments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: file_extensions file_extensions_file_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.file_extensions
    ADD CONSTRAINT file_extensions_file_type_id_fkey FOREIGN KEY (file_type_id) REFERENCES public.file_types(file_type_id);


--
-- Name: identifications identifications_occurrence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.identifications
    ADD CONSTRAINT identifications_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES public.occurrence(occurrence_id) ON DELETE CASCADE;


--
-- Name: identifications identifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.identifications
    ADD CONSTRAINT identifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: make_specimen make_specimen_specimen_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.make_specimen
    ADD CONSTRAINT make_specimen_specimen_id_fkey FOREIGN KEY (specimen_id) REFERENCES public.specimen(specimen_id) ON DELETE CASCADE;


--
-- Name: make_specimen make_specimen_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.make_specimen
    ADD CONSTRAINT make_specimen_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: observation_methods observation_methods_pageid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.observation_methods
    ADD CONSTRAINT observation_methods_pageid_fkey FOREIGN KEY (pageid) REFERENCES public.wiki_pages(page_id);


--
-- Name: observations observations_occurrence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES public.occurrence(occurrence_id) ON DELETE CASCADE;


--
-- Name: observations observations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: occurrence occurrence_classification_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_classification_id_fkey FOREIGN KEY (classification_id) REFERENCES public.classification_json(classification_id);


--
-- Name: occurrence occurrence_place_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(place_id);


--
-- Name: occurrence occurrence_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: occurrence occurrence_workstation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_workstation_id_fkey FOREIGN KEY (workstation_id) REFERENCES public.workstation(workstation_id);


--
-- Name: places places_place_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_place_name_id_fkey FOREIGN KEY (place_name_id) REFERENCES public.place_names_json(place_name_id);


--
-- Name: project_members project_members_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id);


--
-- Name: specimen_methods specimen_methods_page_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.specimen_methods
    ADD CONSTRAINT specimen_methods_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.wiki_pages(page_id);


--
-- Name: specimen specimen_occurrence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.specimen
    ADD CONSTRAINT specimen_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES public.occurrence(occurrence_id) ON DELETE CASCADE;


--
-- Name: workstation_user workstation_user_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.workstation_user
    ADD CONSTRAINT workstation_user_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: workstation_user workstation_user_workstation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.workstation_user
    ADD CONSTRAINT workstation_user_workstation_id_fkey FOREIGN KEY (workstation_id) REFERENCES public.workstation(workstation_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict BNK9tzMTJm5GiO5D1GBcLe0ffZdi4Vjgf8mMb62rfielcvhoL1woaZeXsrfBsGm

